#!/bin/bash

# start a local web server with appengine war file
# dev <app name> <api version> <port>
WORKSPACE_ROOT="$(git rev-parse --show-toplevel)"
APP_NAME="${1:-gascriptsv2}"
API_VERSION="${2:-1.0}"
PORT="${3:-9080}"
echo dev ${APP_NAME} ${API_VERSION} ${PORT}

if docker ps -a | grep ${APP_NAME} ; then
  docker rm -f ${APP_NAME}
fi
cid=$(docker run \
  -p $PORT:8080 \
  -d \
  -v "$(git rev-parse --show-toplevel)":/apps/workspace \
  --name $APP_NAME \
  appengine \
  bash -c "dev_appserver.sh --address=0.0.0.0 --port=8080 /apps/workspace/target/${APP_NAME}-${API_VERSION}")

function cleanup() {
  echo "Shutting down server"
  docker stop $cid
  docker rm $cid
  exit 0
}

trap cleanup EXIT

docker logs -f $cid
exit 0
